import {VariableType} from "@/shared/store/slices/variablesSlice/types.ts";

export const data: VariableType[] = [
    {
        id: "1",
        variableName: "paid base EOP",
        tags: ["base", "EOP"],
        status: "опубликована",
        actualDate: "Август 2024",
        username: "Vasya",
        activity:'05.01.2025',
        chartData: [
            {
                month: "January",
                desktop1: 186,
                desktop2: 246,
                desktop3: 326,
                mobile: 80,
            },
            {
                month: "February",
                desktop1: 186,
                desktop2: 286,
                desktop3: 386,
                mobile: 200,
            },
            {
                month: "March",
                desktop1: 756,
                desktop2: 123,
                desktop3: 222,
                mobile: 120,
            },
            {
                month: "April",
                desktop1: 432,
                desktop2: 286,
                desktop3: 123,
                mobile: 190,
            },
            {
                month: "May",
                desktop1: 123,
                desktop2: 444,
                desktop3: 222,
                mobile: 130,
            },
            {
                month: "June",
                desktop1: 321,
                desktop2: 346,
                desktop3: 215,
                mobile: 140,
            },
            {
                month: "July",
                desktop1: 186,
                desktop2: 246,
                desktop3: 326,
                mobile: 80,
            },
            {
                month: "August",
                desktop1: 186,
                desktop2: 286,
                desktop3: 386,
                mobile: 200,
            },
            {
                month: "September",
                desktop1: 756,
                desktop2: 123,
                desktop3: 222,
                mobile: 120,
            },
            {
                month: "October",
                desktop1: 432,
                desktop2: 286,
                desktop3: 123,
                mobile: 190,
            },
            {
                month: "November",
                desktop1: 123,
                desktop2: 444,
                desktop3: 222,
                mobile: 130,
            },
            {
                month: "December",
                desktop1: 321,
                desktop2: 346,
                desktop3: 215,
                mobile: 140,
            },
        ],
    },
    {
        id: "2",
        variableName: "revenue product cloud",
        tags: ["revenue", "cloud"],
        status: "опубликована",
        actualDate: "Сентябрь 2024",
        username: "Vasya",
        activity:'05.01.2025',
        chartData: [
            {
                month: "January",
                desktop1: 321,
                desktop2: 213,
                desktop3: 876,
                mobile: 123,
            },
            {
                month: "February",
                desktop1: 543,
                desktop2: 342,
                desktop3: 345,
                mobile: 123,
            },
            {
                month: "March",
                desktop1: 21,
                desktop2: 543,
                desktop3: 222,
                mobile: 120,
            },
            {
                month: "April",
                desktop1: 123,
                desktop2: 173,
                desktop3: 123,
                mobile: 432,
            },
            {
                month: "May",
                desktop1: 222,
                desktop2: 111,
                desktop3: 333,
                mobile: 123,
            },
            {
                month: "June",
                desktop1: 321,
                desktop2: 346,
                desktop3: 215,
                mobile: 140,
            },
        ],
    },
    {
        id: "3",
        variableName: "inflow paid base",
        tags: ["base"],
        status: "черновик",
        actualDate: "Август 2024",
        username: "Vasya",
        activity:'05.01.2025',
        chartData: [
            {
                month: "January",
                desktop1: 186,
                desktop2: 246,
                desktop3: 326,
                mobile: 80,
            },
            {
                month: "February",
                desktop1: 186,
                desktop2: 286,
                desktop3: 386,
                mobile: 200,
            },
            {
                month: "March",
                desktop1: 756,
                desktop2: 123,
                desktop3: 222,
                mobile: 120,
            },
            {
                month: "April",
                desktop1: 432,
                desktop2: 286,
                desktop3: 123,
                mobile: 190,
            },
            {
                month: "May",
                desktop1: 123,
                desktop2: 444,
                desktop3: 222,
                mobile: 130,
            },
            {
                month: "June",
                desktop1: 321,
                desktop2: 346,
                desktop3: 215,
                mobile: 140,
            },
        ],
    },
];